version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: url_shortener_postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=docker
    ports:
      - "5432:5432"